name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t 1213117686/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t 1213117686/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u 1213117686 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push 1213117686/devops-qr-code-backend:latest
          docker push 1213117686/devops-qr-code-frontend:latest
          
